### PR TITLE
Don't panic on extraneous tokens, return Error

### PR DESCRIPTION
**Pull request by killercup**
Yes, technically this will most likely be a programmer error, but since
it's hard to prove correctness right now, I'd rather err on the side of
not blowing everything up. (Most of the cases I've run into are even
recoverable.)

### CODE REVIEW

**Comment by killercup** [comment]
Based #17

**Comment by CAD97** [comment]
With the log there to help trace it, this is definitely a good change. In general, it's probably better to replace most panics with a descriptive error.

That said, I'm not sure exactly how recoverable this error ends up being, because much of the code is written with the assumption that there are two kinds of errors only: recoverable (`NoMatch`) and fatal, where the fatal should be propagated up basically always. I suspect that an ordered choice where the first option gets `Extraneous` will bubble that error up as fatal. Of course, currently it panics, so this is an improvement still.

**Comment by killercup** [comment]
> I suspect that an ordered choice where the first option gets Extraneous will bubble that error up as fatal.

Sorry, not sure I understand what you mean by this.

> Of course, currently it panics, so this is an improvement still.

I hope this means you're okay with merging this :)

I've just pushed another commit to also not emit a panic call for enum variants.

**Comment by CAD97** [comment]
Yep, less panicking is always good.

**Pull request merged**
